### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by clayjohn** [cprogrammer1994/ModernGL#86]
I've been trying to get this to run on Linux and it seems to either be very difficult or downright impossible. I was able to get it running great on windows, but on linux I run into all sorts of problems. The closest I could get was using the linux-support branch, but even then when I would try to import ModernGL in code it would throw an error saying there was an undefined reference in the .so file. 

Additionally, I tried to get version 2.4.1 working but had issues because my computer doesn't request a 3.3 context by default and there was no ability to specify which version to use as far as I know. 

I noticed from old issues that linux has been a problem in the past and that you don't have a machine to actively test on. If that's the case then I'd love to help any way I can!

**Comment by cprogrammer1994** [comment]
https://github.com/cprogrammer1994/ModernGL/tree/linux-support

I am testing on a virtual machine that lacks OpenGL 4.x. Currently the context creation is not implemented for linux.

This log is from my VM: (changes were not yet pushed to github)

```
Processing dependencies for ModernGL-beta==3.1.1
Finished processing dependencies for ModernGL-beta==3.1.1
$ python3 -m ModernGL
Vendor:
Renderer: Gallium 0.4 on SVGA3D; build: RELEASE;  LLVM;
Version: 3.0 Mesa 12.0.6
```

We will have linux support soon.

**Comment by clayjohn** [comment]
That's great to hear! I'm happy to help any way I can if you need it. 

I look forward to following the progress of this project!

**Comment by cprogrammer1994** [comment]
Please try installing ModernGL from [linux-support](https://github.com/cprogrammer1994/ModernGL/tree/linux-support)

And run [this example](https://github.com/cprogrammer1994/ModernGL/blob/linux-support/examples/PyQt5/test.py).

_make sure you don't run the example from the project root (otherwise it will import the ModernGL folder)._

**Comment by clayjohn** [comment]
It works great! I was even able to get the standalone example to run as well by adjusting the shaders to use glsl version 130 because my computer will only create a version 3.3 context by request.

**Comment by anvth** [comment]
Hey, this project is awesome. I am having trouble building this on my Ubuntu 16.04 box. Would be great if someone could help me out. This is the error I get:

> 
> 
> ModernGL$ python setup.py build
> running build
> running build_py
> running build_ext
> building 'ModernGL.ModernGL' extension
> i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/Program.cpp -o build/temp.linux-i686-2.7/src/Program.o -std=c++11
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from src/Program.cpp:3:0:
> src/Error.hpp:8:2: error: ‘PyException_HEAD’ does not name a type
>   PyException_HEAD
>   ^
> src/Program.cpp: In function ‘void MGLProgram_Invalidate(MGLProgram*)’:
> src/Program.cpp:375:11: error: ‘struct MGLProgram’ has no member named ‘ob_base’
>   program->ob_base.ob_type = &MGLInvalidObject_Type;
>            ^
> src/Program.cpp: In function ‘void MGLProgram_Compile(MGLProgram*, PyObject*)’:
> src/Program.cpp:413:69: error: ‘PyUnicode_AsUTF8’ was not declared in this scope
>      varyings_array[i] = PyUnicode_AsUTF8(PyList_GET_ITEM(outputs, i));
>                                                                      ^
> error: command 'i686-linux-gnu-gcc' failed with exit status 1
> 
> 

PS: I use Python 2.7, seeing the above log,  I do not that is the problem though.

**Comment by clayjohn** [comment]
I just tried to build with python 2.7 and I received the same error. Looks like you'll have to use python 3.

**Comment by anvth** [comment]
Thanks for confirming it. I will try and see if there can be simple fix for this. AFAIK, 2.7 is still widely used

**Comment by cprogrammer1994** [comment]
`PyException_HEAD` is not defined according to your log.

```
#ifndef PyException_HEAD
#define PyException_HEAD PyObject_HEAD PyObject *dict;\
             PyObject *args; PyObject *traceback;\
             PyObject *context; PyObject *cause;
#endif
```

Hopefully will solve the problem.

**Comment by cprogrammer1994** [comment]
I just opened a new [issue](https://github.com/cprogrammer1994/ModernGL/issues/87) for the 2.7 build failure.

**Comment by cprogrammer1994** [comment]
Added OpenGL 3.3 context creation in LinuxContext.cpp

**Comment by cprogrammer1994** [comment]
merged changes to master
New release: [3.1.2](https://pypi.python.org/pypi/ModernGL/3.1.2)
